// <auto-generated />
namespace Idea_Collecting_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSummary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSummary));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051217297_AddSummary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
